import Foundation
import CMacOSSensing

public typealias WindowMetadataFFI = CMacOSSensing_WindowMetadataFFI
public typealias OCRResultFFI = CMacOSSensing_OCRResultFFI
public typealias ClaudeSessionFFI = CMacOSSensing_ClaudeSessionFFI
